name: "\U0001F4A5 New DNS"
description: "suggest to add new DNS"
title: "[New DNS]:"
labels: ["type: DNS :sob:"]
body:
  - type: input
    attributes:
      label: "IP address of DNS"
      description: "example: 4.2.2.4, 8.8.8.8"
      placeholder: "your suggested DNS"
