name: "\U0001F680 Feature Request"
description: "I have a suggestion \U0001F63B!"
title: "[Parser]:"
labels: ["type: enhancement :wolf:"]
body:
  - type: checkboxes
    attributes:
      label: "Is there an existing issue that is already proposing this?"
      description: "Please search [here](./?q=is%3Aissue) to see if an issue already exists for the feature you are requesting"
      options:
      - label: "I have searched the existing issues"
        required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Is your feature request related to a problem? Please describe it"
      description: "A clear and concise description of what the problem is"
      placeholder: |
        I have an issue when ...

  - type: checkboxes
    validations:
      required: false
    attributes:
      label: "💻 In which operating systems have you tested?"
      options:
        - label: macOS
        - label: Windows
        - label: Linux
