name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --force

      - name: Install electron-builder
        run: npm i electron-builder -g

      - name: Build
        run: npm run build